# Generated by Django 4.2.1 on 2023-05-11 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 22, 8, 13, 390016)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 22, 8, 13, 389995)),
        ),
    ]
